on:
  push:
    branches:
      - master 
  pull_request:
      types: [closed]
      branches:
          - master 

name: Bundle and Publish Sources
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest
    env: 
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run bundle
      - run: npx typedoc -out bundles/docs
        continue-on-error: true

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
